// <auto-generated />
namespace First_API.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class tblBlogers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tblBlogers));
        
        string IMigrationMetadata.Id
        {
            get { return "202102221641408_tblBlogers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
